# Application configuration file
# This file can be used to override default configuration values

# Application settings
app:
  name: "go-http-server"
  version: "1.0.0"
  env: "development"
  debug: true

# Database configuration
database:
  type: "memory"  # Options: postgresql, opengauss, memory
  host: "localhost"
  port: 5432
  user: "postgres"
  password: ""
  database: "server_tpl"
  ssl_mode: "disable"
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: "1h"

# Redis configuration
redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  pool_size: 10
  min_idle_conns: 5
  max_retries: 3
  dial_timeout: "5s"

# Log configuration
log:
  level: "info"
  format: "json"
  output: "stdout"
  file_path: "logs/app.log"
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true
  fields:
    service: "go-http-server"
    version: "1.0.0"
    environment: "development"
  buffer_size: 1024
  async: true

# Server configuration
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"
  cors:
    allowed_origins: ["http://localhost:3000"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["Content-Type", "Authorization"]
    allow_credentials: true
    max_age: 86400

# Monitor configuration
monitor:
  prometheus:
    enabled: true
    path: "/metrics"
    port: 9090
  pprof:
    enabled: false
    path_prefix: "/debug/pprof"
    port: 6060
